# Generated by Django 5.2.17 on 2026-08-13 14:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('canvas_client_id', models.CharField(blank=True, help_text='Canvas developer key ID.', max_length=100)),
                ('canvas_client_secret_encrypted', models.TextField(blank=True)),
                ('enforces_scopes', models.BooleanField(default=True, help_text="Send an explicit scope list to Canvas. Match this to the 'Enforce Scopes' setting on the developer key.")),
                ('scopes', models.JSONField(blank=True, default=list, help_text='Canvas scope strings, e.g. ["url:GET|/api/v1/courses"].')),
                ('allowed_methods', models.JSONField(blank=True, default=list, help_text='HTTP methods apps on this tier may proxy. Empty means all.')),
                ('path_rules', models.JSONField(blank=True, default=list, help_text='Allowlist entries: [{"methods": ["GET"], "pattern": "^/api/v1/courses(/|$)"}]. Empty means every path is allowed.')),
                ('denied_patterns', models.JSONField(blank=True, default=list, help_text='Regexes always refused on this tier, checked before the allowlist.')),
                ('allow_masquerade', models.BooleanField(default=False, help_text='Permit as_user_id= masquerading. Only enable for a tier whose developer key is trusted with account-admin acting-as rights.')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('sort_order', 'slug'),
            },
        ),
        migrations.CreateModel(
            name='ProxyApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True, help_text='What the app does and why it needs this access.')),
                ('homepage_url', models.URLField(blank=True)),
                ('redirect_uris', models.JSONField(default=list)),
                ('client_id', models.CharField(editable=False, max_length=64, unique=True)),
                ('client_secret_hash', models.CharField(blank=True, max_length=255)),
                ('client_secret_hint', models.CharField(blank=True, max_length=16)),
                ('secret_rotated_at', models.DateTimeField(blank=True, null=True)),
                ('is_public_client', models.BooleanField(default=False, help_text='Public clients (SPAs, mobile, CLI) hold no secret and must use PKCE.')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('suspended', 'Suspended')], default='draft', max_length=20)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apps', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_apps', to=settings.AUTH_USER_MODEL)),
                ('tier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='apps', to='registry.accesstier')),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['status'], name='registry_pr_status_da1f71_idx')],
            },
        ),
    ]
