# Generated by Django 5.2.17 on 2026-08-17 16:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='proxyapp',
            name='allowed_methods',
            field=models.JSONField(blank=True, default=list, help_text='HTTP methods this app may use upstream. Empty means all.'),
        ),
        migrations.AddField(
            model_name='proxyapp',
            name='api_base_url',
            field=models.URLField(blank=True, help_text='Base URL of the third-party API, e.g. https://api.example.com/v2', max_length=500),
        ),
        migrations.AddField(
            model_name='proxyapp',
            name='credential_name',
            field=models.CharField(blank=True, help_text='Header or query parameter name, for those credential styles.', max_length=100),
        ),
        migrations.AddField(
            model_name='proxyapp',
            name='credential_style',
            field=models.CharField(choices=[('none', 'No credentials (public API)'), ('bearer', 'Authorization: Bearer <secret>'), ('basic', 'HTTP Basic (client id + secret)'), ('header', 'Custom header'), ('query', 'Query parameter')], default='none', max_length=20),
        ),
        migrations.AddField(
            model_name='proxyapp',
            name='kind',
            field=models.CharField(choices=[('canvas', 'Canvas API'), ('external', 'External API')], default='canvas', max_length=20),
        ),
        migrations.AddField(
            model_name='proxyapp',
            name='path_rules',
            field=models.JSONField(blank=True, default=list, help_text='Optional allowlist: [{"methods": ["GET"], "pattern": "^/v2/items"}]. Empty means every path under the base URL.'),
        ),
        migrations.AddField(
            model_name='proxyapp',
            name='upstream_client_id',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='proxyapp',
            name='upstream_client_secret_encrypted',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='proxyapp',
            name='tier',
            field=models.ForeignKey(blank=True, help_text='Canvas apps only.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='apps', to='registry.accesstier'),
        ),
    ]
