# Generated by Django 5.2.17 on 2026-08-21 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0002_proxyapp_allowed_methods_proxyapp_api_base_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='proxyapp',
            name='allow_anonymous',
            field=models.BooleanField(default=False, help_text='Allow requests without a bearer token, gated by Origin. External apps only. Requests arrive at /ext/public/<client_id>/…'),
        ),
    ]
