# Generated by Django 5.2.17 on 2026-08-13 14:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('oauth', '0001_initial'),
        ('registry', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('canvas_user_id', models.CharField(blank=True, max_length=64)),
                ('method', models.CharField(max_length=10)),
                ('path', models.CharField(max_length=500)),
                ('query', models.CharField(blank=True, max_length=1000)),
                ('status_code', models.PositiveIntegerField(null=True)),
                ('duration_ms', models.PositiveIntegerField(null=True)),
                ('denied_reason', models.CharField(blank=True, max_length=255)),
                ('client_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('app', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='request_logs', to='registry.proxyapp')),
                ('grant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='request_logs', to='oauth.canvasgrant')),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['app', '-created_at'], name='gateway_req_app_id_41ea15_idx'), models.Index(fields=['-created_at'], name='gateway_req_created_20a06a_idx')],
            },
        ),
    ]
