# Generated by Django 5.2.17 on 2026-08-13 14:02

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('registry', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CanvasGrant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('canvas_user_id', models.CharField(max_length=64)),
                ('canvas_user_name', models.CharField(blank=True, max_length=255)),
                ('canvas_global_id', models.CharField(blank=True, max_length=64)),
                ('access_token_encrypted', models.TextField()),
                ('refresh_token_encrypted', models.TextField(blank=True)),
                ('access_token_expires_at', models.DateTimeField(blank=True, null=True)),
                ('scopes', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grants', to='registry.proxyapp')),
                ('tier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grants', to='registry.accesstier')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='AuthorizationCode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code_digest', models.CharField(max_length=64, unique=True)),
                ('redirect_uri', models.URLField(max_length=500)),
                ('code_challenge', models.CharField(blank=True, max_length=128)),
                ('code_challenge_method', models.CharField(blank=True, max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('consumed_at', models.DateTimeField(blank=True, null=True)),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auth_codes', to='registry.proxyapp')),
                ('grant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auth_codes', to='oauth.canvasgrant')),
            ],
        ),
        migrations.CreateModel(
            name='ProxyToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('access_token_digest', models.CharField(max_length=64, unique=True)),
                ('refresh_token_digest', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('expires_at', models.DateTimeField()),
                ('refresh_expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('grant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tokens', to='oauth.canvasgrant')),
                ('replaced_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replaces', to='oauth.proxytoken')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='AuthorizationRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('redirect_uri', models.URLField(max_length=500)),
                ('client_state', models.CharField(blank=True, max_length=500)),
                ('proxy_state', models.CharField(max_length=128, unique=True)),
                ('code_challenge', models.CharField(blank=True, max_length=128)),
                ('code_challenge_method', models.CharField(blank=True, max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('consumed_at', models.DateTimeField(blank=True, null=True)),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auth_requests', to='registry.proxyapp')),
            ],
            options={
                'indexes': [models.Index(fields=['expires_at'], name='oauth_autho_expires_65ac7e_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='canvasgrant',
            index=models.Index(fields=['app', 'canvas_user_id'], name='oauth_canva_app_id_824244_idx'),
        ),
        migrations.AddIndex(
            model_name='canvasgrant',
            index=models.Index(fields=['revoked_at'], name='oauth_canva_revoked_03fc1d_idx'),
        ),
        migrations.AddIndex(
            model_name='authorizationcode',
            index=models.Index(fields=['expires_at'], name='oauth_autho_expires_9bd032_idx'),
        ),
        migrations.AddIndex(
            model_name='proxytoken',
            index=models.Index(fields=['expires_at'], name='oauth_proxy_expires_8f112e_idx'),
        ),
    ]
