# Generated by Django 5.2.17 on 2026-08-17 16:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oauth', '0001_initial'),
        ('registry', '0002_proxyapp_allowed_methods_proxyapp_api_base_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='canvasgrant',
            name='access_token_encrypted',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='canvasgrant',
            name='tier',
            field=models.ForeignKey(blank=True, help_text='Canvas apps only; external apps have no developer key.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='grants', to='registry.accesstier'),
        ),
    ]
